ALTER ROLE [db_datareader] ADD MEMBER [ADMINDOM\ODAAdmin]
GO
ALTER ROLE [db_datareader] ADD MEMBER [ADMINDOM\ODARO]
GO
ALTER ROLE [db_datareader] ADD MEMBER [ADMINDOM\PBIContractors]
GO
ALTER ROLE [db_datareader] ADD MEMBER [PowerBI]
GO
