CREATE TABLE [dbo].[DimAssessment]
(
[AssessmentKey] [int] NOT NULL IDENTITY(1, 1),
[_sourceKey] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AssessmentCategoryDescriptor_CodeValue] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AssessmentCategoryDescriptor_Description] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AssessmentFamilyTitle] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdaptiveAssessment_Indicator] [bit] NOT NULL,
[AssessmentIdentifier] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AssessmentTitle] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AssessmentScore_AssessmentReportingMethodDescriptor_CodeValue] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AssessmentScore_AssessmentReportingMethodDescriptor_Description] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AssessmentScore_ResultDatatypeTypeDescriptor_CodeValue] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AssessmentScore_ResultDatatypeTypeDescriptor_Description] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AssessmentPerformanceLevel_Descriptor_CodeValue] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AssessmentPerformanceLevel_Descriptor_Description] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AssessmentPerformanceLevel_AssessmentReportingMethodDescriptor_CodeValue] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AssessmentPerformanceLevel_AssessmentReportingMethodDescriptor_Description] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AssessmentPerformanceLevel_ResultDatatypeType_DescriptorCodeValue] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AssessmentPerformanceLevel_ResultDatatypeType_DescriptorDescription] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ParentObjectiveAssessmentIdentificationCode] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ParentObjectiveAssessmentIdentificationDescription] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ParentObjectiveAssessmentScore_AssessmentReportingMethodDescriptor_CodeValue] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ParentObjectiveAssessmentScore_AssessmentReportingMethodDescriptor_Description] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ParentObjectiveAssessmentScore_ResultDatatypeType_Descriptor_CodeValue] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ParentObjectiveAssessmentScore_ResultDatatypeType_Descriptor_Description] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ParentObjectiveAssessmentPerformanceLevel_DescriptorCodeValue] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ParentObjectiveAssessmentPerformanceLevel_DescriptorDescriptorDescription] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ParentObjectiveAssessmentPerformanceLevel_AssessmentReportingMethodDescriptor_CodeValue] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ParentObjectivePerformanceLevel_AssessmentReportingMethodDescriptor_DescriptorDescription] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ParentObjectiveAssessmentPerformanceLevel_ResultDatatypeType_DescriptorCodeValue] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ParentObjectiveAssessmentPerformanceLevel_ResultDatatypeType_DescriptorDescription] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ChildObjectiveAssessmentIdentificationCode] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ChildObjectiveAssessmentIdentificationDescription] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ChildObjectiveAssessmentScore_AssessmentReportingMethodDescriptor_CodeValue] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ChildObjectiveAssessmentScore_AssessmentReportingMethodDescriptor_Description] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ChildObjectiveAssessmentScore_ResultDatatypeType_Descriptor_CodeValue] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ChildObjectiveAssessmentScore_ResultDatatypeType_Descriptor_Description] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ChildObjectiveAssessmentPerformanceLevel_Descriptor_CodeValue] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ChildObjectiveAssessmentPerformanceLevel_Descriptor_Description] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ChildObjectiveAssessmentPerformanceLevel_AssessmentReportingMethodDescriptor_CodeValue] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ChildObjectiveAssessmentPerformanceLevel_AssessmentReportingMethodDescriptor_Description] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ChildObjectiveAssessmentPerformanceLevel_ResultDatatypeType_Descriptor_CodeValue] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ChildObjectiveAssessmentPerformanceLevel_ResultDatatypeType_Descriptor_Description] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ValidFrom] [datetime] NOT NULL,
[ValidTo] [datetime] NOT NULL,
[IsCurrent] [bit] NOT NULL,
[LineageKey] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DimAssessment] ADD CONSTRAINT [PK_DimAssessment] PRIMARY KEY CLUSTERED  ([AssessmentKey]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DimAssessment] ADD CONSTRAINT [FK_DimAssessment_LineageKey] FOREIGN KEY ([LineageKey]) REFERENCES [dbo].[Lineage] ([LineageKey])
GO
