CREATE TABLE [dbo].[DimStudent]
(
[StudentKey] [int] NOT NULL IDENTITY(1, 1),
[_sourceKey] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[StudentUniqueId] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StateId] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SchoolKey] [int] NOT NULL,
[ShortNameOfInstitution] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NameOfInstitution] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GradeLevelDescriptor_CodeValue] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GradeLevelDescriptor_Description] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FirstName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MiddleInitial] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastSurname] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FullName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BirthDate] [date] NOT NULL,
[CurrentAge] [int] NOT NULL,
[SchoolYearAdmitted] [int] NOT NULL,
[Graduation_Indicator] [bit] NULL,
[Homeroom] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HomeroomTeacher] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SexType_Code] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SexType_Description] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SexType_Male_Indicator] [bit] NOT NULL,
[SexType_Female_Indicator] [bit] NOT NULL,
[SexType_NotSelected_Indicator] [bit] NOT NULL,
[RaceCode] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RaceDescription] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Race_AmericanIndianAlaskanNative_Indicator] [bit] NOT NULL,
[Race_Asian_Indicator] [bit] NOT NULL,
[Race_BlackAfricaAmerican_Indicator] [bit] NOT NULL,
[Race_NativeHawaiianPacificIslander_Indicator] [bit] NOT NULL,
[Race_White_Indicator] [bit] NOT NULL,
[Race_MultiRace_Indicator] [bit] NOT NULL,
[Race_ChooseNotRespond_Indicator] [bit] NOT NULL,
[Race_Other_Indicator] [bit] NOT NULL,
[EthnicityCode] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EthnicityDescription] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EthnicityHispanicLatino_Indicator] [bit] NOT NULL,
[IEP_Indicator] [bit] NOT NULL,
[LimitedEnglishProficiencyDescriptor_CodeValue] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LimitedEnglishProficiencyDescriptor_Description] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LimitedEnglishProficiency_EnglishLearner_Indicator] [bit] NOT NULL,
[LimitedEnglishProficiency_Former_Indicator] [bit] NOT NULL,
[LimitedEnglishProficiency_NotEnglisLearner_Indicator] [bit] NOT NULL,
[EconomicDisadvantage_Indicator] [bit] NOT NULL,
[EntryGradeLevelReasonType_CodeValue] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EntryGradeLevelReasonType_Description] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EntryGradeLevelReasonType_PromotionVariableProgress_Indicator] [bit] NOT NULL,
[EntryGradeLevelReasonType_PromotionOther_Indicator] [bit] NOT NULL,
[EntryGradeLevelReasonType_NonpromotionFailedToMeetTestingRequirements_Indicator] [bit] NOT NULL,
[EntryGradeLevelReasonType_NonpromotionIllness_Indicator] [bit] NOT NULL,
[EntryGradeLevelReasonType_NonpromotionInsufficientCredits_Indicator] [bit] NOT NULL,
[EntryGradeLevelReasonType_NonpromotionProlongedAbsence_Indicator] [bit] NOT NULL,
[EntryGradeLevelReasonType_NonpromotionImmaturity_Indicator] [bit] NOT NULL,
[EntryDate] [datetime2] NOT NULL,
[EntrySchoolYear] [int] NOT NULL,
[EntryCode] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ExitWithdrawDate] [datetime2] NULL,
[ExitWithdrawSchoolYear] [int] NOT NULL,
[ExitWithdrawCode] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValidFrom] [datetime] NOT NULL,
[ValidTo] [datetime] NOT NULL,
[IsCurrent] [bit] NOT NULL,
[LineageKey] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DimStudent] ADD CONSTRAINT [PK_DimStudent] PRIMARY KEY CLUSTERED  ([StudentKey]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DimStudent] ADD CONSTRAINT [FK_DimStudent_LineageKey] FOREIGN KEY ([LineageKey]) REFERENCES [dbo].[Lineage] ([LineageKey])
GO
ALTER TABLE [dbo].[DimStudent] ADD CONSTRAINT [FK_DimStudent_SchoolKey] FOREIGN KEY ([SchoolKey]) REFERENCES [dbo].[DimSchool] ([SchoolKey])
GO
