CREATE TABLE [Raw_LegacyDW].[DisciplineIncidents]
(
[BPS_Student_ID] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SKL_SCHOOL_ID] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SKL_SCHOOL_NAME] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CND_INCIDENT_ID] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CND_INCIDENT_CODE] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CND_INCIDENT_DATE] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CND_INCIDENT_TIME] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CND_INCIDENT_LOCATION] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CND_INCIDENT_DESCRIPTION] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACT_PENALTY_TIME] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACT_ACTION_CODE] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
