IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ADMINDOM\ODAAdmin')
CREATE LOGIN [ADMINDOM\ODAAdmin] FROM WINDOWS
GO
CREATE USER [ADMINDOM\ODAAdmin] FOR LOGIN [ADMINDOM\ODAAdmin]
GO
